### ISSUE TITLE
Official Container Image

### ISSUE THREAD

**Issue by madflojo** [orijtech/tickeryzer#11]
Is it possible to have an official container image created and published via DockerHub or GitHub Container Repo?

This would help users pull in the image and use it via CI/CD pipelines. I.E. One could use the container in a GitHub Action.

**Comment by kirbyquerby** [comment]
Thanks for the feedback, Benjamin! We have an image now :D
https://github.com/orijtech/tickeryzer/pkgs/container/tickeryzer

README updates will come soon as well :)
